// Code generated by github.com/Khan/genqlient, DO NOT EDIT.

package cloudflaregraphql

import (
	"context"
	"time"

	"github.com/Khan/genqlient/graphql"
)

// GetWorkerAnalyticsResponse is returned by GetWorkerAnalytics on success.
type GetWorkerAnalyticsResponse struct {
	Viewer *GetWorkerAnalyticsViewer `json:"viewer,omitempty"`
}

// GetViewer returns GetWorkerAnalyticsResponse.Viewer, and is useful for accessing the field via an interface.
func (v *GetWorkerAnalyticsResponse) GetViewer() *GetWorkerAnalyticsViewer { return v.Viewer }

// GetWorkerAnalyticsViewer includes the requested fields of the GraphQL type viewer.
type GetWorkerAnalyticsViewer struct {
	Zones []GetWorkerAnalyticsViewerZonesZone `json:"zones,omitempty"`
}

// GetZones returns GetWorkerAnalyticsViewer.Zones, and is useful for accessing the field via an interface.
func (v *GetWorkerAnalyticsViewer) GetZones() []GetWorkerAnalyticsViewerZonesZone { return v.Zones }

// GetWorkerAnalyticsViewerZonesZone includes the requested fields of the GraphQL type zone.
type GetWorkerAnalyticsViewerZonesZone struct {
	// Workers subrequests with adaptive sampling
	SubrequestsData []GetWorkerAnalyticsViewerZonesZoneSubrequestsDataZoneWorkersZoneSubrequestsAdaptiveGroups `json:"subrequestsData,omitempty"`
	// Workers invocations with adaptive sampling
	BandwidthData []GetWorkerAnalyticsViewerZonesZoneBandwidthDataZoneWorkersZoneInvocationsAdaptiveGroups `json:"bandwidthData,omitempty"`
	// Workers invocations with adaptive sampling
	StatusCodesData []GetWorkerAnalyticsViewerZonesZoneStatusCodesDataZoneWorkersZoneInvocationsAdaptiveGroups `json:"statusCodesData,omitempty"`
	// Workers invocations with adaptive sampling
	TotalRequestsData []GetWorkerAnalyticsViewerZonesZoneTotalRequestsDataZoneWorkersZoneInvocationsAdaptiveGroups `json:"totalRequestsData,omitempty"`
}

// GetSubrequestsData returns GetWorkerAnalyticsViewerZonesZone.SubrequestsData, and is useful for accessing the field via an interface.
func (v *GetWorkerAnalyticsViewerZonesZone) GetSubrequestsData() []GetWorkerAnalyticsViewerZonesZoneSubrequestsDataZoneWorkersZoneSubrequestsAdaptiveGroups {
	return v.SubrequestsData
}

// GetBandwidthData returns GetWorkerAnalyticsViewerZonesZone.BandwidthData, and is useful for accessing the field via an interface.
func (v *GetWorkerAnalyticsViewerZonesZone) GetBandwidthData() []GetWorkerAnalyticsViewerZonesZoneBandwidthDataZoneWorkersZoneInvocationsAdaptiveGroups {
	return v.BandwidthData
}

// GetStatusCodesData returns GetWorkerAnalyticsViewerZonesZone.StatusCodesData, and is useful for accessing the field via an interface.
func (v *GetWorkerAnalyticsViewerZonesZone) GetStatusCodesData() []GetWorkerAnalyticsViewerZonesZoneStatusCodesDataZoneWorkersZoneInvocationsAdaptiveGroups {
	return v.StatusCodesData
}

// GetTotalRequestsData returns GetWorkerAnalyticsViewerZonesZone.TotalRequestsData, and is useful for accessing the field via an interface.
func (v *GetWorkerAnalyticsViewerZonesZone) GetTotalRequestsData() []GetWorkerAnalyticsViewerZonesZoneTotalRequestsDataZoneWorkersZoneInvocationsAdaptiveGroups {
	return v.TotalRequestsData
}

// GetWorkerAnalyticsViewerZonesZoneBandwidthDataZoneWorkersZoneInvocationsAdaptiveGroups includes the requested fields of the GraphQL type ZoneWorkersZoneInvocationsAdaptiveGroups.
// The GraphQL type's documentation follows.
//
// Workers invocations with adaptive sampling
type GetWorkerAnalyticsViewerZonesZoneBandwidthDataZoneWorkersZoneInvocationsAdaptiveGroups struct {
	// The sum of values for a metric per dimension
	Sum *GetWorkerAnalyticsViewerZonesZoneBandwidthDataZoneWorkersZoneInvocationsAdaptiveGroupsSum `json:"sum,omitempty"`
	// List of dimensions to group by
	Dimensions *GetWorkerAnalyticsViewerZonesZoneBandwidthDataZoneWorkersZoneInvocationsAdaptiveGroupsDimensions `json:"dimensions,omitempty"`
}

// GetSum returns GetWorkerAnalyticsViewerZonesZoneBandwidthDataZoneWorkersZoneInvocationsAdaptiveGroups.Sum, and is useful for accessing the field via an interface.
func (v *GetWorkerAnalyticsViewerZonesZoneBandwidthDataZoneWorkersZoneInvocationsAdaptiveGroups) GetSum() *GetWorkerAnalyticsViewerZonesZoneBandwidthDataZoneWorkersZoneInvocationsAdaptiveGroupsSum {
	return v.Sum
}

// GetDimensions returns GetWorkerAnalyticsViewerZonesZoneBandwidthDataZoneWorkersZoneInvocationsAdaptiveGroups.Dimensions, and is useful for accessing the field via an interface.
func (v *GetWorkerAnalyticsViewerZonesZoneBandwidthDataZoneWorkersZoneInvocationsAdaptiveGroups) GetDimensions() *GetWorkerAnalyticsViewerZonesZoneBandwidthDataZoneWorkersZoneInvocationsAdaptiveGroupsDimensions {
	return v.Dimensions
}

// GetWorkerAnalyticsViewerZonesZoneBandwidthDataZoneWorkersZoneInvocationsAdaptiveGroupsDimensions includes the requested fields of the GraphQL type ZoneWorkersZoneInvocationsAdaptiveGroupsDimensions.
type GetWorkerAnalyticsViewerZonesZoneBandwidthDataZoneWorkersZoneInvocationsAdaptiveGroupsDimensions struct {
	// Request datetime, truncated to start of an hour
	DatetimeHour time.Time `json:"datetimeHour"`
}

// GetDatetimeHour returns GetWorkerAnalyticsViewerZonesZoneBandwidthDataZoneWorkersZoneInvocationsAdaptiveGroupsDimensions.DatetimeHour, and is useful for accessing the field via an interface.
func (v *GetWorkerAnalyticsViewerZonesZoneBandwidthDataZoneWorkersZoneInvocationsAdaptiveGroupsDimensions) GetDatetimeHour() time.Time {
	return v.DatetimeHour
}

// GetWorkerAnalyticsViewerZonesZoneBandwidthDataZoneWorkersZoneInvocationsAdaptiveGroupsSum includes the requested fields of the GraphQL type ZoneWorkersZoneInvocationsAdaptiveGroupsSum.
type GetWorkerAnalyticsViewerZonesZoneBandwidthDataZoneWorkersZoneInvocationsAdaptiveGroupsSum struct {
	// Bandwidth (in bytes) returned to eyeball
	ResponseBodySize uint64 `json:"responseBodySize"`
}

// GetResponseBodySize returns GetWorkerAnalyticsViewerZonesZoneBandwidthDataZoneWorkersZoneInvocationsAdaptiveGroupsSum.ResponseBodySize, and is useful for accessing the field via an interface.
func (v *GetWorkerAnalyticsViewerZonesZoneBandwidthDataZoneWorkersZoneInvocationsAdaptiveGroupsSum) GetResponseBodySize() uint64 {
	return v.ResponseBodySize
}

// GetWorkerAnalyticsViewerZonesZoneStatusCodesDataZoneWorkersZoneInvocationsAdaptiveGroups includes the requested fields of the GraphQL type ZoneWorkersZoneInvocationsAdaptiveGroups.
// The GraphQL type's documentation follows.
//
// Workers invocations with adaptive sampling
type GetWorkerAnalyticsViewerZonesZoneStatusCodesDataZoneWorkersZoneInvocationsAdaptiveGroups struct {
	// The sum of values for a metric per dimension
	Sum *GetWorkerAnalyticsViewerZonesZoneStatusCodesDataZoneWorkersZoneInvocationsAdaptiveGroupsSum `json:"sum,omitempty"`
	// List of dimensions to group by
	Dimensions *GetWorkerAnalyticsViewerZonesZoneStatusCodesDataZoneWorkersZoneInvocationsAdaptiveGroupsDimensions `json:"dimensions,omitempty"`
}

// GetSum returns GetWorkerAnalyticsViewerZonesZoneStatusCodesDataZoneWorkersZoneInvocationsAdaptiveGroups.Sum, and is useful for accessing the field via an interface.
func (v *GetWorkerAnalyticsViewerZonesZoneStatusCodesDataZoneWorkersZoneInvocationsAdaptiveGroups) GetSum() *GetWorkerAnalyticsViewerZonesZoneStatusCodesDataZoneWorkersZoneInvocationsAdaptiveGroupsSum {
	return v.Sum
}

// GetDimensions returns GetWorkerAnalyticsViewerZonesZoneStatusCodesDataZoneWorkersZoneInvocationsAdaptiveGroups.Dimensions, and is useful for accessing the field via an interface.
func (v *GetWorkerAnalyticsViewerZonesZoneStatusCodesDataZoneWorkersZoneInvocationsAdaptiveGroups) GetDimensions() *GetWorkerAnalyticsViewerZonesZoneStatusCodesDataZoneWorkersZoneInvocationsAdaptiveGroupsDimensions {
	return v.Dimensions
}

// GetWorkerAnalyticsViewerZonesZoneStatusCodesDataZoneWorkersZoneInvocationsAdaptiveGroupsDimensions includes the requested fields of the GraphQL type ZoneWorkersZoneInvocationsAdaptiveGroupsDimensions.
type GetWorkerAnalyticsViewerZonesZoneStatusCodesDataZoneWorkersZoneInvocationsAdaptiveGroupsDimensions struct {
	// Origin HTTP response code
	HttpResponseStatus uint16 `json:"httpResponseStatus"`
	// Request datetime, truncated to start of an hour
	DatetimeHour time.Time `json:"datetimeHour"`
}

// GetHttpResponseStatus returns GetWorkerAnalyticsViewerZonesZoneStatusCodesDataZoneWorkersZoneInvocationsAdaptiveGroupsDimensions.HttpResponseStatus, and is useful for accessing the field via an interface.
func (v *GetWorkerAnalyticsViewerZonesZoneStatusCodesDataZoneWorkersZoneInvocationsAdaptiveGroupsDimensions) GetHttpResponseStatus() uint16 {
	return v.HttpResponseStatus
}

// GetDatetimeHour returns GetWorkerAnalyticsViewerZonesZoneStatusCodesDataZoneWorkersZoneInvocationsAdaptiveGroupsDimensions.DatetimeHour, and is useful for accessing the field via an interface.
func (v *GetWorkerAnalyticsViewerZonesZoneStatusCodesDataZoneWorkersZoneInvocationsAdaptiveGroupsDimensions) GetDatetimeHour() time.Time {
	return v.DatetimeHour
}

// GetWorkerAnalyticsViewerZonesZoneStatusCodesDataZoneWorkersZoneInvocationsAdaptiveGroupsSum includes the requested fields of the GraphQL type ZoneWorkersZoneInvocationsAdaptiveGroupsSum.
type GetWorkerAnalyticsViewerZonesZoneStatusCodesDataZoneWorkersZoneInvocationsAdaptiveGroupsSum struct {
	// Number of sub-requests issued by the edge worker
	Subrequests uint64 `json:"subrequests"`
}

// GetSubrequests returns GetWorkerAnalyticsViewerZonesZoneStatusCodesDataZoneWorkersZoneInvocationsAdaptiveGroupsSum.Subrequests, and is useful for accessing the field via an interface.
func (v *GetWorkerAnalyticsViewerZonesZoneStatusCodesDataZoneWorkersZoneInvocationsAdaptiveGroupsSum) GetSubrequests() uint64 {
	return v.Subrequests
}

// GetWorkerAnalyticsViewerZonesZoneSubrequestsDataZoneWorkersZoneSubrequestsAdaptiveGroups includes the requested fields of the GraphQL type ZoneWorkersZoneSubrequestsAdaptiveGroups.
// The GraphQL type's documentation follows.
//
// Workers subrequests with adaptive sampling
type GetWorkerAnalyticsViewerZonesZoneSubrequestsDataZoneWorkersZoneSubrequestsAdaptiveGroups struct {
	// The sum of values for a metric per dimension
	Sum *GetWorkerAnalyticsViewerZonesZoneSubrequestsDataZoneWorkersZoneSubrequestsAdaptiveGroupsSum `json:"sum,omitempty"`
	// List of dimensions to group by
	Dimensions *GetWorkerAnalyticsViewerZonesZoneSubrequestsDataZoneWorkersZoneSubrequestsAdaptiveGroupsDimensions `json:"dimensions,omitempty"`
}

// GetSum returns GetWorkerAnalyticsViewerZonesZoneSubrequestsDataZoneWorkersZoneSubrequestsAdaptiveGroups.Sum, and is useful for accessing the field via an interface.
func (v *GetWorkerAnalyticsViewerZonesZoneSubrequestsDataZoneWorkersZoneSubrequestsAdaptiveGroups) GetSum() *GetWorkerAnalyticsViewerZonesZoneSubrequestsDataZoneWorkersZoneSubrequestsAdaptiveGroupsSum {
	return v.Sum
}

// GetDimensions returns GetWorkerAnalyticsViewerZonesZoneSubrequestsDataZoneWorkersZoneSubrequestsAdaptiveGroups.Dimensions, and is useful for accessing the field via an interface.
func (v *GetWorkerAnalyticsViewerZonesZoneSubrequestsDataZoneWorkersZoneSubrequestsAdaptiveGroups) GetDimensions() *GetWorkerAnalyticsViewerZonesZoneSubrequestsDataZoneWorkersZoneSubrequestsAdaptiveGroupsDimensions {
	return v.Dimensions
}

// GetWorkerAnalyticsViewerZonesZoneSubrequestsDataZoneWorkersZoneSubrequestsAdaptiveGroupsDimensions includes the requested fields of the GraphQL type ZoneWorkersZoneSubrequestsAdaptiveGroupsDimensions.
type GetWorkerAnalyticsViewerZonesZoneSubrequestsDataZoneWorkersZoneSubrequestsAdaptiveGroupsDimensions struct {
	// Cache status
	CacheStatus uint64 `json:"cacheStatus"`
	// Request datetime, truncated to start of an hour
	DatetimeHour time.Time `json:"datetimeHour"`
}

// GetCacheStatus returns GetWorkerAnalyticsViewerZonesZoneSubrequestsDataZoneWorkersZoneSubrequestsAdaptiveGroupsDimensions.CacheStatus, and is useful for accessing the field via an interface.
func (v *GetWorkerAnalyticsViewerZonesZoneSubrequestsDataZoneWorkersZoneSubrequestsAdaptiveGroupsDimensions) GetCacheStatus() uint64 {
	return v.CacheStatus
}

// GetDatetimeHour returns GetWorkerAnalyticsViewerZonesZoneSubrequestsDataZoneWorkersZoneSubrequestsAdaptiveGroupsDimensions.DatetimeHour, and is useful for accessing the field via an interface.
func (v *GetWorkerAnalyticsViewerZonesZoneSubrequestsDataZoneWorkersZoneSubrequestsAdaptiveGroupsDimensions) GetDatetimeHour() time.Time {
	return v.DatetimeHour
}

// GetWorkerAnalyticsViewerZonesZoneSubrequestsDataZoneWorkersZoneSubrequestsAdaptiveGroupsSum includes the requested fields of the GraphQL type ZoneWorkersZoneSubrequestsAdaptiveGroupsSum.
type GetWorkerAnalyticsViewerZonesZoneSubrequestsDataZoneWorkersZoneSubrequestsAdaptiveGroupsSum struct {
	// Number of subrequests issued by a worker
	Subrequests uint64 `json:"subrequests"`
}

// GetSubrequests returns GetWorkerAnalyticsViewerZonesZoneSubrequestsDataZoneWorkersZoneSubrequestsAdaptiveGroupsSum.Subrequests, and is useful for accessing the field via an interface.
func (v *GetWorkerAnalyticsViewerZonesZoneSubrequestsDataZoneWorkersZoneSubrequestsAdaptiveGroupsSum) GetSubrequests() uint64 {
	return v.Subrequests
}

// GetWorkerAnalyticsViewerZonesZoneTotalRequestsDataZoneWorkersZoneInvocationsAdaptiveGroups includes the requested fields of the GraphQL type ZoneWorkersZoneInvocationsAdaptiveGroups.
// The GraphQL type's documentation follows.
//
// Workers invocations with adaptive sampling
type GetWorkerAnalyticsViewerZonesZoneTotalRequestsDataZoneWorkersZoneInvocationsAdaptiveGroups struct {
	// The sum of values for a metric per dimension
	Sum *GetWorkerAnalyticsViewerZonesZoneTotalRequestsDataZoneWorkersZoneInvocationsAdaptiveGroupsSum `json:"sum,omitempty"`
	// List of dimensions to group by
	Dimensions *GetWorkerAnalyticsViewerZonesZoneTotalRequestsDataZoneWorkersZoneInvocationsAdaptiveGroupsDimensions `json:"dimensions,omitempty"`
}

// GetSum returns GetWorkerAnalyticsViewerZonesZoneTotalRequestsDataZoneWorkersZoneInvocationsAdaptiveGroups.Sum, and is useful for accessing the field via an interface.
func (v *GetWorkerAnalyticsViewerZonesZoneTotalRequestsDataZoneWorkersZoneInvocationsAdaptiveGroups) GetSum() *GetWorkerAnalyticsViewerZonesZoneTotalRequestsDataZoneWorkersZoneInvocationsAdaptiveGroupsSum {
	return v.Sum
}

// GetDimensions returns GetWorkerAnalyticsViewerZonesZoneTotalRequestsDataZoneWorkersZoneInvocationsAdaptiveGroups.Dimensions, and is useful for accessing the field via an interface.
func (v *GetWorkerAnalyticsViewerZonesZoneTotalRequestsDataZoneWorkersZoneInvocationsAdaptiveGroups) GetDimensions() *GetWorkerAnalyticsViewerZonesZoneTotalRequestsDataZoneWorkersZoneInvocationsAdaptiveGroupsDimensions {
	return v.Dimensions
}

// GetWorkerAnalyticsViewerZonesZoneTotalRequestsDataZoneWorkersZoneInvocationsAdaptiveGroupsDimensions includes the requested fields of the GraphQL type ZoneWorkersZoneInvocationsAdaptiveGroupsDimensions.
type GetWorkerAnalyticsViewerZonesZoneTotalRequestsDataZoneWorkersZoneInvocationsAdaptiveGroupsDimensions struct {
	// Status of the worker invocation
	Status string `json:"status"`
	// Request datetime, truncated to start of an hour
	DatetimeHour time.Time `json:"datetimeHour"`
}

// GetStatus returns GetWorkerAnalyticsViewerZonesZoneTotalRequestsDataZoneWorkersZoneInvocationsAdaptiveGroupsDimensions.Status, and is useful for accessing the field via an interface.
func (v *GetWorkerAnalyticsViewerZonesZoneTotalRequestsDataZoneWorkersZoneInvocationsAdaptiveGroupsDimensions) GetStatus() string {
	return v.Status
}

// GetDatetimeHour returns GetWorkerAnalyticsViewerZonesZoneTotalRequestsDataZoneWorkersZoneInvocationsAdaptiveGroupsDimensions.DatetimeHour, and is useful for accessing the field via an interface.
func (v *GetWorkerAnalyticsViewerZonesZoneTotalRequestsDataZoneWorkersZoneInvocationsAdaptiveGroupsDimensions) GetDatetimeHour() time.Time {
	return v.DatetimeHour
}

// GetWorkerAnalyticsViewerZonesZoneTotalRequestsDataZoneWorkersZoneInvocationsAdaptiveGroupsSum includes the requested fields of the GraphQL type ZoneWorkersZoneInvocationsAdaptiveGroupsSum.
type GetWorkerAnalyticsViewerZonesZoneTotalRequestsDataZoneWorkersZoneInvocationsAdaptiveGroupsSum struct {
	// Sum of Requests
	Requests uint64 `json:"requests"`
}

// GetRequests returns GetWorkerAnalyticsViewerZonesZoneTotalRequestsDataZoneWorkersZoneInvocationsAdaptiveGroupsSum.Requests, and is useful for accessing the field via an interface.
func (v *GetWorkerAnalyticsViewerZonesZoneTotalRequestsDataZoneWorkersZoneInvocationsAdaptiveGroupsSum) GetRequests() uint64 {
	return v.Requests
}

// GetZoneAnalyticsResponse is returned by GetZoneAnalytics on success.
type GetZoneAnalyticsResponse struct {
	Viewer *GetZoneAnalyticsViewer `json:"viewer,omitempty"`
}

// GetViewer returns GetZoneAnalyticsResponse.Viewer, and is useful for accessing the field via an interface.
func (v *GetZoneAnalyticsResponse) GetViewer() *GetZoneAnalyticsViewer { return v.Viewer }

// GetZoneAnalyticsViewer includes the requested fields of the GraphQL type viewer.
type GetZoneAnalyticsViewer struct {
	Zones []GetZoneAnalyticsViewerZonesZone `json:"zones,omitempty"`
}

// GetZones returns GetZoneAnalyticsViewer.Zones, and is useful for accessing the field via an interface.
func (v *GetZoneAnalyticsViewer) GetZones() []GetZoneAnalyticsViewerZonesZone { return v.Zones }

// GetZoneAnalyticsViewerZonesZone includes the requested fields of the GraphQL type zone.
type GetZoneAnalyticsViewerZonesZone struct {
	// Daily rollups of request data
	Totals []GetZoneAnalyticsViewerZonesZoneTotalsZoneHttpRequests1dGroups `json:"totals,omitempty"`
	// Daily rollups of request data
	Zones []GetZoneAnalyticsViewerZonesZoneZonesZoneHttpRequests1dGroups `json:"zones,omitempty"`
}

// GetTotals returns GetZoneAnalyticsViewerZonesZone.Totals, and is useful for accessing the field via an interface.
func (v *GetZoneAnalyticsViewerZonesZone) GetTotals() []GetZoneAnalyticsViewerZonesZoneTotalsZoneHttpRequests1dGroups {
	return v.Totals
}

// GetZones returns GetZoneAnalyticsViewerZonesZone.Zones, and is useful for accessing the field via an interface.
func (v *GetZoneAnalyticsViewerZonesZone) GetZones() []GetZoneAnalyticsViewerZonesZoneZonesZoneHttpRequests1dGroups {
	return v.Zones
}

// GetZoneAnalyticsViewerZonesZoneTotalsZoneHttpRequests1dGroups includes the requested fields of the GraphQL type ZoneHttpRequests1dGroups.
// The GraphQL type's documentation follows.
//
// Daily rollups of request data
type GetZoneAnalyticsViewerZonesZoneTotalsZoneHttpRequests1dGroups struct {
	// The number of unique values for a metric per dimension
	Uniq *GetZoneAnalyticsViewerZonesZoneTotalsZoneHttpRequests1dGroupsUniq `json:"uniq,omitempty"`
}

// GetUniq returns GetZoneAnalyticsViewerZonesZoneTotalsZoneHttpRequests1dGroups.Uniq, and is useful for accessing the field via an interface.
func (v *GetZoneAnalyticsViewerZonesZoneTotalsZoneHttpRequests1dGroups) GetUniq() *GetZoneAnalyticsViewerZonesZoneTotalsZoneHttpRequests1dGroupsUniq {
	return v.Uniq
}

// GetZoneAnalyticsViewerZonesZoneTotalsZoneHttpRequests1dGroupsUniq includes the requested fields of the GraphQL type ZoneHttpRequests1dGroupsUniq.
type GetZoneAnalyticsViewerZonesZoneTotalsZoneHttpRequests1dGroupsUniq struct {
	// A number of unique IPs
	Uniques uint64 `json:"uniques"`
}

// GetUniques returns GetZoneAnalyticsViewerZonesZoneTotalsZoneHttpRequests1dGroupsUniq.Uniques, and is useful for accessing the field via an interface.
func (v *GetZoneAnalyticsViewerZonesZoneTotalsZoneHttpRequests1dGroupsUniq) GetUniques() uint64 {
	return v.Uniques
}

// GetZoneAnalyticsViewerZonesZoneZonesZoneHttpRequests1dGroups includes the requested fields of the GraphQL type ZoneHttpRequests1dGroups.
// The GraphQL type's documentation follows.
//
// Daily rollups of request data
type GetZoneAnalyticsViewerZonesZoneZonesZoneHttpRequests1dGroups struct {
	// List of dimensions to group by
	Dimensions *GetZoneAnalyticsViewerZonesZoneZonesZoneHttpRequests1dGroupsDimensions `json:"dimensions,omitempty"`
	// The number of unique values for a metric per dimension
	Uniq *GetZoneAnalyticsViewerZonesZoneZonesZoneHttpRequests1dGroupsUniq `json:"uniq,omitempty"`
	// The sum of values for a metric per dimension
	Sum *GetZoneAnalyticsViewerZonesZoneZonesZoneHttpRequests1dGroupsSum `json:"sum,omitempty"`
}

// GetDimensions returns GetZoneAnalyticsViewerZonesZoneZonesZoneHttpRequests1dGroups.Dimensions, and is useful for accessing the field via an interface.
func (v *GetZoneAnalyticsViewerZonesZoneZonesZoneHttpRequests1dGroups) GetDimensions() *GetZoneAnalyticsViewerZonesZoneZonesZoneHttpRequests1dGroupsDimensions {
	return v.Dimensions
}

// GetUniq returns GetZoneAnalyticsViewerZonesZoneZonesZoneHttpRequests1dGroups.Uniq, and is useful for accessing the field via an interface.
func (v *GetZoneAnalyticsViewerZonesZoneZonesZoneHttpRequests1dGroups) GetUniq() *GetZoneAnalyticsViewerZonesZoneZonesZoneHttpRequests1dGroupsUniq {
	return v.Uniq
}

// GetSum returns GetZoneAnalyticsViewerZonesZoneZonesZoneHttpRequests1dGroups.Sum, and is useful for accessing the field via an interface.
func (v *GetZoneAnalyticsViewerZonesZoneZonesZoneHttpRequests1dGroups) GetSum() *GetZoneAnalyticsViewerZonesZoneZonesZoneHttpRequests1dGroupsSum {
	return v.Sum
}

// GetZoneAnalyticsViewerZonesZoneZonesZoneHttpRequests1dGroupsDimensions includes the requested fields of the GraphQL type ZoneHttpRequests1dGroupsDimensions.
type GetZoneAnalyticsViewerZonesZoneZonesZoneHttpRequests1dGroupsDimensions struct {
	// Request date
	Timeslot string `json:"timeslot"`
}

// GetTimeslot returns GetZoneAnalyticsViewerZonesZoneZonesZoneHttpRequests1dGroupsDimensions.Timeslot, and is useful for accessing the field via an interface.
func (v *GetZoneAnalyticsViewerZonesZoneZonesZoneHttpRequests1dGroupsDimensions) GetTimeslot() string {
	return v.Timeslot
}

// GetZoneAnalyticsViewerZonesZoneZonesZoneHttpRequests1dGroupsSum includes the requested fields of the GraphQL type ZoneHttpRequests1dGroupsSum.
type GetZoneAnalyticsViewerZonesZoneZonesZoneHttpRequests1dGroupsSum struct {
	BrowserMap []GetZoneAnalyticsViewerZonesZoneZonesZoneHttpRequests1dGroupsSumBrowserMapZoneHttpRequests1dGroupsBrowserMapElem `json:"browserMap,omitempty"`
	// Bytes returned to client
	Bytes uint64 `json:"bytes"`
	// Bytes returned to client from cache
	CachedBytes uint64 `json:"cachedBytes"`
	// Requests served from cache
	CachedRequests uint64                                                                                                                    `json:"cachedRequests"`
	ContentTypeMap []GetZoneAnalyticsViewerZonesZoneZonesZoneHttpRequests1dGroupsSumContentTypeMapZoneHttpRequests1dGroupsContentTypeMapElem `json:"contentTypeMap,omitempty"`
	ClientSSLMap   []GetZoneAnalyticsViewerZonesZoneZonesZoneHttpRequests1dGroupsSumClientSSLMapZoneHttpRequests1dGroupsClientSSLMapElem     `json:"clientSSLMap,omitempty"`
	CountryMap     []GetZoneAnalyticsViewerZonesZoneZonesZoneHttpRequests1dGroupsSumCountryMapZoneHttpRequests1dGroupsCountryMapElem         `json:"countryMap,omitempty"`
	// Bytes returned to client using SSL/TLS protocol
	EncryptedBytes uint64 `json:"encryptedBytes"`
	// Requests served using SSL/TLS protocol
	EncryptedRequests uint64                                                                                                            `json:"encryptedRequests"`
	IpClassMap        []GetZoneAnalyticsViewerZonesZoneZonesZoneHttpRequests1dGroupsSumIpClassMapZoneHttpRequests1dGroupsIpClassMapElem `json:"ipClassMap,omitempty"`
	// Successful requests for HTML content
	PageViews         uint64                                                                                                                          `json:"pageViews"`
	Requests          uint64                                                                                                                          `json:"requests"`
	ResponseStatusMap []GetZoneAnalyticsViewerZonesZoneZonesZoneHttpRequests1dGroupsSumResponseStatusMapZoneHttpRequests1dGroupsResponseStatusMapElem `json:"responseStatusMap,omitempty"`
	// Requests classified as threats
	Threats          uint64                                                                                                                        `json:"threats"`
	ThreatPathingMap []GetZoneAnalyticsViewerZonesZoneZonesZoneHttpRequests1dGroupsSumThreatPathingMapZoneHttpRequests1dGroupsThreatPathingMapElem `json:"threatPathingMap,omitempty"`
}

// GetBrowserMap returns GetZoneAnalyticsViewerZonesZoneZonesZoneHttpRequests1dGroupsSum.BrowserMap, and is useful for accessing the field via an interface.
func (v *GetZoneAnalyticsViewerZonesZoneZonesZoneHttpRequests1dGroupsSum) GetBrowserMap() []GetZoneAnalyticsViewerZonesZoneZonesZoneHttpRequests1dGroupsSumBrowserMapZoneHttpRequests1dGroupsBrowserMapElem {
	return v.BrowserMap
}

// GetBytes returns GetZoneAnalyticsViewerZonesZoneZonesZoneHttpRequests1dGroupsSum.Bytes, and is useful for accessing the field via an interface.
func (v *GetZoneAnalyticsViewerZonesZoneZonesZoneHttpRequests1dGroupsSum) GetBytes() uint64 {
	return v.Bytes
}

// GetCachedBytes returns GetZoneAnalyticsViewerZonesZoneZonesZoneHttpRequests1dGroupsSum.CachedBytes, and is useful for accessing the field via an interface.
func (v *GetZoneAnalyticsViewerZonesZoneZonesZoneHttpRequests1dGroupsSum) GetCachedBytes() uint64 {
	return v.CachedBytes
}

// GetCachedRequests returns GetZoneAnalyticsViewerZonesZoneZonesZoneHttpRequests1dGroupsSum.CachedRequests, and is useful for accessing the field via an interface.
func (v *GetZoneAnalyticsViewerZonesZoneZonesZoneHttpRequests1dGroupsSum) GetCachedRequests() uint64 {
	return v.CachedRequests
}

// GetContentTypeMap returns GetZoneAnalyticsViewerZonesZoneZonesZoneHttpRequests1dGroupsSum.ContentTypeMap, and is useful for accessing the field via an interface.
func (v *GetZoneAnalyticsViewerZonesZoneZonesZoneHttpRequests1dGroupsSum) GetContentTypeMap() []GetZoneAnalyticsViewerZonesZoneZonesZoneHttpRequests1dGroupsSumContentTypeMapZoneHttpRequests1dGroupsContentTypeMapElem {
	return v.ContentTypeMap
}

// GetClientSSLMap returns GetZoneAnalyticsViewerZonesZoneZonesZoneHttpRequests1dGroupsSum.ClientSSLMap, and is useful for accessing the field via an interface.
func (v *GetZoneAnalyticsViewerZonesZoneZonesZoneHttpRequests1dGroupsSum) GetClientSSLMap() []GetZoneAnalyticsViewerZonesZoneZonesZoneHttpRequests1dGroupsSumClientSSLMapZoneHttpRequests1dGroupsClientSSLMapElem {
	return v.ClientSSLMap
}

// GetCountryMap returns GetZoneAnalyticsViewerZonesZoneZonesZoneHttpRequests1dGroupsSum.CountryMap, and is useful for accessing the field via an interface.
func (v *GetZoneAnalyticsViewerZonesZoneZonesZoneHttpRequests1dGroupsSum) GetCountryMap() []GetZoneAnalyticsViewerZonesZoneZonesZoneHttpRequests1dGroupsSumCountryMapZoneHttpRequests1dGroupsCountryMapElem {
	return v.CountryMap
}

// GetEncryptedBytes returns GetZoneAnalyticsViewerZonesZoneZonesZoneHttpRequests1dGroupsSum.EncryptedBytes, and is useful for accessing the field via an interface.
func (v *GetZoneAnalyticsViewerZonesZoneZonesZoneHttpRequests1dGroupsSum) GetEncryptedBytes() uint64 {
	return v.EncryptedBytes
}

// GetEncryptedRequests returns GetZoneAnalyticsViewerZonesZoneZonesZoneHttpRequests1dGroupsSum.EncryptedRequests, and is useful for accessing the field via an interface.
func (v *GetZoneAnalyticsViewerZonesZoneZonesZoneHttpRequests1dGroupsSum) GetEncryptedRequests() uint64 {
	return v.EncryptedRequests
}

// GetIpClassMap returns GetZoneAnalyticsViewerZonesZoneZonesZoneHttpRequests1dGroupsSum.IpClassMap, and is useful for accessing the field via an interface.
func (v *GetZoneAnalyticsViewerZonesZoneZonesZoneHttpRequests1dGroupsSum) GetIpClassMap() []GetZoneAnalyticsViewerZonesZoneZonesZoneHttpRequests1dGroupsSumIpClassMapZoneHttpRequests1dGroupsIpClassMapElem {
	return v.IpClassMap
}

// GetPageViews returns GetZoneAnalyticsViewerZonesZoneZonesZoneHttpRequests1dGroupsSum.PageViews, and is useful for accessing the field via an interface.
func (v *GetZoneAnalyticsViewerZonesZoneZonesZoneHttpRequests1dGroupsSum) GetPageViews() uint64 {
	return v.PageViews
}

// GetRequests returns GetZoneAnalyticsViewerZonesZoneZonesZoneHttpRequests1dGroupsSum.Requests, and is useful for accessing the field via an interface.
func (v *GetZoneAnalyticsViewerZonesZoneZonesZoneHttpRequests1dGroupsSum) GetRequests() uint64 {
	return v.Requests
}

// GetResponseStatusMap returns GetZoneAnalyticsViewerZonesZoneZonesZoneHttpRequests1dGroupsSum.ResponseStatusMap, and is useful for accessing the field via an interface.
func (v *GetZoneAnalyticsViewerZonesZoneZonesZoneHttpRequests1dGroupsSum) GetResponseStatusMap() []GetZoneAnalyticsViewerZonesZoneZonesZoneHttpRequests1dGroupsSumResponseStatusMapZoneHttpRequests1dGroupsResponseStatusMapElem {
	return v.ResponseStatusMap
}

// GetThreats returns GetZoneAnalyticsViewerZonesZoneZonesZoneHttpRequests1dGroupsSum.Threats, and is useful for accessing the field via an interface.
func (v *GetZoneAnalyticsViewerZonesZoneZonesZoneHttpRequests1dGroupsSum) GetThreats() uint64 {
	return v.Threats
}

// GetThreatPathingMap returns GetZoneAnalyticsViewerZonesZoneZonesZoneHttpRequests1dGroupsSum.ThreatPathingMap, and is useful for accessing the field via an interface.
func (v *GetZoneAnalyticsViewerZonesZoneZonesZoneHttpRequests1dGroupsSum) GetThreatPathingMap() []GetZoneAnalyticsViewerZonesZoneZonesZoneHttpRequests1dGroupsSumThreatPathingMapZoneHttpRequests1dGroupsThreatPathingMapElem {
	return v.ThreatPathingMap
}

// GetZoneAnalyticsViewerZonesZoneZonesZoneHttpRequests1dGroupsSumBrowserMapZoneHttpRequests1dGroupsBrowserMapElem includes the requested fields of the GraphQL type ZoneHttpRequests1dGroupsBrowserMapElem.
type GetZoneAnalyticsViewerZonesZoneZonesZoneHttpRequests1dGroupsSumBrowserMapZoneHttpRequests1dGroupsBrowserMapElem struct {
	// Successful requests for HTML content
	PageViews uint64 `json:"pageViews"`
	// Browser type
	Key string `json:"key"`
}

// GetPageViews returns GetZoneAnalyticsViewerZonesZoneZonesZoneHttpRequests1dGroupsSumBrowserMapZoneHttpRequests1dGroupsBrowserMapElem.PageViews, and is useful for accessing the field via an interface.
func (v *GetZoneAnalyticsViewerZonesZoneZonesZoneHttpRequests1dGroupsSumBrowserMapZoneHttpRequests1dGroupsBrowserMapElem) GetPageViews() uint64 {
	return v.PageViews
}

// GetKey returns GetZoneAnalyticsViewerZonesZoneZonesZoneHttpRequests1dGroupsSumBrowserMapZoneHttpRequests1dGroupsBrowserMapElem.Key, and is useful for accessing the field via an interface.
func (v *GetZoneAnalyticsViewerZonesZoneZonesZoneHttpRequests1dGroupsSumBrowserMapZoneHttpRequests1dGroupsBrowserMapElem) GetKey() string {
	return v.Key
}

// GetZoneAnalyticsViewerZonesZoneZonesZoneHttpRequests1dGroupsSumClientSSLMapZoneHttpRequests1dGroupsClientSSLMapElem includes the requested fields of the GraphQL type ZoneHttpRequests1dGroupsClientSSLMapElem.
type GetZoneAnalyticsViewerZonesZoneZonesZoneHttpRequests1dGroupsSumClientSSLMapZoneHttpRequests1dGroupsClientSSLMapElem struct {
	Requests uint64 `json:"requests"`
	// Protocol version
	Key string `json:"key"`
}

// GetRequests returns GetZoneAnalyticsViewerZonesZoneZonesZoneHttpRequests1dGroupsSumClientSSLMapZoneHttpRequests1dGroupsClientSSLMapElem.Requests, and is useful for accessing the field via an interface.
func (v *GetZoneAnalyticsViewerZonesZoneZonesZoneHttpRequests1dGroupsSumClientSSLMapZoneHttpRequests1dGroupsClientSSLMapElem) GetRequests() uint64 {
	return v.Requests
}

// GetKey returns GetZoneAnalyticsViewerZonesZoneZonesZoneHttpRequests1dGroupsSumClientSSLMapZoneHttpRequests1dGroupsClientSSLMapElem.Key, and is useful for accessing the field via an interface.
func (v *GetZoneAnalyticsViewerZonesZoneZonesZoneHttpRequests1dGroupsSumClientSSLMapZoneHttpRequests1dGroupsClientSSLMapElem) GetKey() string {
	return v.Key
}

// GetZoneAnalyticsViewerZonesZoneZonesZoneHttpRequests1dGroupsSumContentTypeMapZoneHttpRequests1dGroupsContentTypeMapElem includes the requested fields of the GraphQL type ZoneHttpRequests1dGroupsContentTypeMapElem.
type GetZoneAnalyticsViewerZonesZoneZonesZoneHttpRequests1dGroupsSumContentTypeMapZoneHttpRequests1dGroupsContentTypeMapElem struct {
	// Bytes returned to client
	Bytes    uint64 `json:"bytes"`
	Requests uint64 `json:"requests"`
	// Content type returned to client
	Key string `json:"key"`
}

// GetBytes returns GetZoneAnalyticsViewerZonesZoneZonesZoneHttpRequests1dGroupsSumContentTypeMapZoneHttpRequests1dGroupsContentTypeMapElem.Bytes, and is useful for accessing the field via an interface.
func (v *GetZoneAnalyticsViewerZonesZoneZonesZoneHttpRequests1dGroupsSumContentTypeMapZoneHttpRequests1dGroupsContentTypeMapElem) GetBytes() uint64 {
	return v.Bytes
}

// GetRequests returns GetZoneAnalyticsViewerZonesZoneZonesZoneHttpRequests1dGroupsSumContentTypeMapZoneHttpRequests1dGroupsContentTypeMapElem.Requests, and is useful for accessing the field via an interface.
func (v *GetZoneAnalyticsViewerZonesZoneZonesZoneHttpRequests1dGroupsSumContentTypeMapZoneHttpRequests1dGroupsContentTypeMapElem) GetRequests() uint64 {
	return v.Requests
}

// GetKey returns GetZoneAnalyticsViewerZonesZoneZonesZoneHttpRequests1dGroupsSumContentTypeMapZoneHttpRequests1dGroupsContentTypeMapElem.Key, and is useful for accessing the field via an interface.
func (v *GetZoneAnalyticsViewerZonesZoneZonesZoneHttpRequests1dGroupsSumContentTypeMapZoneHttpRequests1dGroupsContentTypeMapElem) GetKey() string {
	return v.Key
}

// GetZoneAnalyticsViewerZonesZoneZonesZoneHttpRequests1dGroupsSumCountryMapZoneHttpRequests1dGroupsCountryMapElem includes the requested fields of the GraphQL type ZoneHttpRequests1dGroupsCountryMapElem.
type GetZoneAnalyticsViewerZonesZoneZonesZoneHttpRequests1dGroupsSumCountryMapZoneHttpRequests1dGroupsCountryMapElem struct {
	// Bytes returned to client
	Bytes    uint64 `json:"bytes"`
	Requests uint64 `json:"requests"`
	// Requests classified as threats
	Threats uint64 `json:"threats"`
	// Country from which request originated
	Key string `json:"key"`
}

// GetBytes returns GetZoneAnalyticsViewerZonesZoneZonesZoneHttpRequests1dGroupsSumCountryMapZoneHttpRequests1dGroupsCountryMapElem.Bytes, and is useful for accessing the field via an interface.
func (v *GetZoneAnalyticsViewerZonesZoneZonesZoneHttpRequests1dGroupsSumCountryMapZoneHttpRequests1dGroupsCountryMapElem) GetBytes() uint64 {
	return v.Bytes
}

// GetRequests returns GetZoneAnalyticsViewerZonesZoneZonesZoneHttpRequests1dGroupsSumCountryMapZoneHttpRequests1dGroupsCountryMapElem.Requests, and is useful for accessing the field via an interface.
func (v *GetZoneAnalyticsViewerZonesZoneZonesZoneHttpRequests1dGroupsSumCountryMapZoneHttpRequests1dGroupsCountryMapElem) GetRequests() uint64 {
	return v.Requests
}

// GetThreats returns GetZoneAnalyticsViewerZonesZoneZonesZoneHttpRequests1dGroupsSumCountryMapZoneHttpRequests1dGroupsCountryMapElem.Threats, and is useful for accessing the field via an interface.
func (v *GetZoneAnalyticsViewerZonesZoneZonesZoneHttpRequests1dGroupsSumCountryMapZoneHttpRequests1dGroupsCountryMapElem) GetThreats() uint64 {
	return v.Threats
}

// GetKey returns GetZoneAnalyticsViewerZonesZoneZonesZoneHttpRequests1dGroupsSumCountryMapZoneHttpRequests1dGroupsCountryMapElem.Key, and is useful for accessing the field via an interface.
func (v *GetZoneAnalyticsViewerZonesZoneZonesZoneHttpRequests1dGroupsSumCountryMapZoneHttpRequests1dGroupsCountryMapElem) GetKey() string {
	return v.Key
}

// GetZoneAnalyticsViewerZonesZoneZonesZoneHttpRequests1dGroupsSumIpClassMapZoneHttpRequests1dGroupsIpClassMapElem includes the requested fields of the GraphQL type ZoneHttpRequests1dGroupsIpClassMapElem.
type GetZoneAnalyticsViewerZonesZoneZonesZoneHttpRequests1dGroupsSumIpClassMapZoneHttpRequests1dGroupsIpClassMapElem struct {
	Requests uint64 `json:"requests"`
	// IP class
	Key string `json:"key"`
}

// GetRequests returns GetZoneAnalyticsViewerZonesZoneZonesZoneHttpRequests1dGroupsSumIpClassMapZoneHttpRequests1dGroupsIpClassMapElem.Requests, and is useful for accessing the field via an interface.
func (v *GetZoneAnalyticsViewerZonesZoneZonesZoneHttpRequests1dGroupsSumIpClassMapZoneHttpRequests1dGroupsIpClassMapElem) GetRequests() uint64 {
	return v.Requests
}

// GetKey returns GetZoneAnalyticsViewerZonesZoneZonesZoneHttpRequests1dGroupsSumIpClassMapZoneHttpRequests1dGroupsIpClassMapElem.Key, and is useful for accessing the field via an interface.
func (v *GetZoneAnalyticsViewerZonesZoneZonesZoneHttpRequests1dGroupsSumIpClassMapZoneHttpRequests1dGroupsIpClassMapElem) GetKey() string {
	return v.Key
}

// GetZoneAnalyticsViewerZonesZoneZonesZoneHttpRequests1dGroupsSumResponseStatusMapZoneHttpRequests1dGroupsResponseStatusMapElem includes the requested fields of the GraphQL type ZoneHttpRequests1dGroupsResponseStatusMapElem.
type GetZoneAnalyticsViewerZonesZoneZonesZoneHttpRequests1dGroupsSumResponseStatusMapZoneHttpRequests1dGroupsResponseStatusMapElem struct {
	Requests uint64 `json:"requests"`
	// HTTP response status code returned to client
	Key uint64 `json:"key"`
}

// GetRequests returns GetZoneAnalyticsViewerZonesZoneZonesZoneHttpRequests1dGroupsSumResponseStatusMapZoneHttpRequests1dGroupsResponseStatusMapElem.Requests, and is useful for accessing the field via an interface.
func (v *GetZoneAnalyticsViewerZonesZoneZonesZoneHttpRequests1dGroupsSumResponseStatusMapZoneHttpRequests1dGroupsResponseStatusMapElem) GetRequests() uint64 {
	return v.Requests
}

// GetKey returns GetZoneAnalyticsViewerZonesZoneZonesZoneHttpRequests1dGroupsSumResponseStatusMapZoneHttpRequests1dGroupsResponseStatusMapElem.Key, and is useful for accessing the field via an interface.
func (v *GetZoneAnalyticsViewerZonesZoneZonesZoneHttpRequests1dGroupsSumResponseStatusMapZoneHttpRequests1dGroupsResponseStatusMapElem) GetKey() uint64 {
	return v.Key
}

// GetZoneAnalyticsViewerZonesZoneZonesZoneHttpRequests1dGroupsSumThreatPathingMapZoneHttpRequests1dGroupsThreatPathingMapElem includes the requested fields of the GraphQL type ZoneHttpRequests1dGroupsThreatPathingMapElem.
type GetZoneAnalyticsViewerZonesZoneZonesZoneHttpRequests1dGroupsSumThreatPathingMapZoneHttpRequests1dGroupsThreatPathingMapElem struct {
	Requests uint64 `json:"requests"`
	// Threat type
	Key string `json:"key"`
}

// GetRequests returns GetZoneAnalyticsViewerZonesZoneZonesZoneHttpRequests1dGroupsSumThreatPathingMapZoneHttpRequests1dGroupsThreatPathingMapElem.Requests, and is useful for accessing the field via an interface.
func (v *GetZoneAnalyticsViewerZonesZoneZonesZoneHttpRequests1dGroupsSumThreatPathingMapZoneHttpRequests1dGroupsThreatPathingMapElem) GetRequests() uint64 {
	return v.Requests
}

// GetKey returns GetZoneAnalyticsViewerZonesZoneZonesZoneHttpRequests1dGroupsSumThreatPathingMapZoneHttpRequests1dGroupsThreatPathingMapElem.Key, and is useful for accessing the field via an interface.
func (v *GetZoneAnalyticsViewerZonesZoneZonesZoneHttpRequests1dGroupsSumThreatPathingMapZoneHttpRequests1dGroupsThreatPathingMapElem) GetKey() string {
	return v.Key
}

// GetZoneAnalyticsViewerZonesZoneZonesZoneHttpRequests1dGroupsUniq includes the requested fields of the GraphQL type ZoneHttpRequests1dGroupsUniq.
type GetZoneAnalyticsViewerZonesZoneZonesZoneHttpRequests1dGroupsUniq struct {
	// A number of unique IPs
	Uniques uint64 `json:"uniques"`
}

// GetUniques returns GetZoneAnalyticsViewerZonesZoneZonesZoneHttpRequests1dGroupsUniq.Uniques, and is useful for accessing the field via an interface.
func (v *GetZoneAnalyticsViewerZonesZoneZonesZoneHttpRequests1dGroupsUniq) GetUniques() uint64 {
	return v.Uniques
}

// __GetWorkerAnalyticsInput is used internally by genqlient
type __GetWorkerAnalyticsInput struct {
	ZoneTag  *string   `json:"zoneTag,omitempty"`
	Datetime time.Time `json:"datetime"`
}

// GetZoneTag returns __GetWorkerAnalyticsInput.ZoneTag, and is useful for accessing the field via an interface.
func (v *__GetWorkerAnalyticsInput) GetZoneTag() *string { return v.ZoneTag }

// GetDatetime returns __GetWorkerAnalyticsInput.Datetime, and is useful for accessing the field via an interface.
func (v *__GetWorkerAnalyticsInput) GetDatetime() time.Time { return v.Datetime }

// __GetZoneAnalyticsInput is used internally by genqlient
type __GetZoneAnalyticsInput struct {
	ZoneTag *string `json:"zoneTag,omitempty"`
	Since   string  `json:"since"`
	Until   string  `json:"until"`
}

// GetZoneTag returns __GetZoneAnalyticsInput.ZoneTag, and is useful for accessing the field via an interface.
func (v *__GetZoneAnalyticsInput) GetZoneTag() *string { return v.ZoneTag }

// GetSince returns __GetZoneAnalyticsInput.Since, and is useful for accessing the field via an interface.
func (v *__GetZoneAnalyticsInput) GetSince() string { return v.Since }

// GetUntil returns __GetZoneAnalyticsInput.Until, and is useful for accessing the field via an interface.
func (v *__GetZoneAnalyticsInput) GetUntil() string { return v.Until }

// The query or mutation executed by GetWorkerAnalytics.
const GetWorkerAnalytics_Operation = `
query GetWorkerAnalytics ($zoneTag: string, $datetime: Time!) {
	viewer {
		zones(filter: {zoneTag:$zoneTag}) {
			subrequestsData: workersZoneSubrequestsAdaptiveGroups(limit: 10000, filter: {datetime_geq:$datetime}) {
				sum {
					subrequests
				}
				dimensions {
					cacheStatus
					datetimeHour
				}
			}
			bandwidthData: workersZoneInvocationsAdaptiveGroups(limit: 10000, filter: {datetime_geq:$datetime}) {
				sum {
					responseBodySize
				}
				dimensions {
					datetimeHour
				}
			}
			statusCodesData: workersZoneInvocationsAdaptiveGroups(limit: 10000, filter: {datetime_geq:$datetime}) {
				sum {
					subrequests
				}
				dimensions {
					httpResponseStatus
					datetimeHour
				}
			}
			totalRequestsData: workersZoneInvocationsAdaptiveGroups(limit: 10000, filter: {datetime_geq:$datetime}) {
				sum {
					requests
				}
				dimensions {
					status
					datetimeHour
				}
			}
		}
	}
}
`

func GetWorkerAnalyticsQuery(
	ctx_ context.Context,
	client_ graphql.Client,
	zoneTag *string,
	datetime time.Time,
) (*GetWorkerAnalyticsResponse, error) {
	req_ := &graphql.Request{
		OpName: "GetWorkerAnalytics",
		Query:  GetWorkerAnalytics_Operation,
		Variables: &__GetWorkerAnalyticsInput{
			ZoneTag:  zoneTag,
			Datetime: datetime,
		},
	}
	var err_ error

	var data_ GetWorkerAnalyticsResponse
	resp_ := &graphql.Response{Data: &data_}

	err_ = client_.MakeRequest(
		ctx_,
		req_,
		resp_,
	)

	return &data_, err_
}

// The query or mutation executed by GetZoneAnalytics.
const GetZoneAnalytics_Operation = `
query GetZoneAnalytics ($zoneTag: string, $since: Date!, $until: Date!) {
	viewer {
		zones(filter: {zoneTag:$zoneTag}) {
			totals: httpRequests1dGroups(limit: 10000, filter: {date_geq:$since,date_lt:$until}) {
				uniq {
					uniques
				}
			}
			zones: httpRequests1dGroups(orderBy: [date_ASC], limit: 10000, filter: {date_geq:$since,date_lt:$until}) {
				dimensions {
					timeslot: date
				}
				uniq {
					uniques
				}
				sum {
					browserMap {
						pageViews
						key: uaBrowserFamily
					}
					bytes
					cachedBytes
					cachedRequests
					contentTypeMap {
						bytes
						requests
						key: edgeResponseContentTypeName
					}
					clientSSLMap {
						requests
						key: clientSSLProtocol
					}
					countryMap {
						bytes
						requests
						threats
						key: clientCountryName
					}
					encryptedBytes
					encryptedRequests
					ipClassMap {
						requests
						key: ipType
					}
					pageViews
					requests
					responseStatusMap {
						requests
						key: edgeResponseStatus
					}
					threats
					threatPathingMap {
						requests
						key: threatPathingName
					}
				}
			}
		}
	}
}
`

func GetZoneAnalyticsQuery(
	ctx_ context.Context,
	client_ graphql.Client,
	zoneTag *string,
	since string,
	until string,
) (*GetZoneAnalyticsResponse, error) {
	req_ := &graphql.Request{
		OpName: "GetZoneAnalytics",
		Query:  GetZoneAnalytics_Operation,
		Variables: &__GetZoneAnalyticsInput{
			ZoneTag: zoneTag,
			Since:   since,
			Until:   until,
		},
	}
	var err_ error

	var data_ GetZoneAnalyticsResponse
	resp_ := &graphql.Response{Data: &data_}

	err_ = client_.MakeRequest(
		ctx_,
		req_,
		resp_,
	)

	return &data_, err_
}
